### ISSUE TITLE
Test my own data

### ISSUE THREAD

**Issue by luoxiaodou** [jnjaby/DISCNet#1]
Why my own data which is smaller than the real data in your dataset can not be processed due to "out of memory"? Is there something wrong in the process of generating the .npy files of my own data?

**Comment by jnjaby** [comment]
We used a single Nvidia V100 GPU, with 32 GB memory, for testing. If you encounter an `out of memory` problem, consider cropping the image into `3x3` or `4x4` sub-images, depending on your GPU memory. Then feed them into the network and merge outputs to get the restored image.
