### ISSUE TITLE
1 dB lower than your pretrained model

### ISSUE THREAD

**Issue by Jian-danai** [jnjaby/DISCNet#12]
Hi, I followed the instructions in your paper and the same settings in your options/DISCNet_train.yml, but after 1000,000 iterations' training, the PSNR is still 1 dB lower than that of your pre-trained model(or what you claimed in your paper). So I was wondering whether there are any other strategies I need to follow during training?

Some important parameters I used: Batch_size: 8, GPU_num: 2, Patch_size: 256.

**Comment by jnjaby** [comment]
Hi, 1 dB difference of PSNR is a large margin. Did you try to evaluate the performance of our pre-trained model to see if your testing settings are correct? Below are the results of each dataset on my machine.

![image](https://user-images.githubusercontent.com/16274959/137095419-ac48ce20-c137-49c1-a675-4d6d17e68b6b.png)
![image](https://user-images.githubusercontent.com/16274959/137097751-77562485-4b65-4ebe-94a3-ed3ad5ed925b.png)

**Comment by Jian-danai** [comment]
Sorry for the inconvenience. There is no problem with your code. I can reproduce the same performance as yours. Thank you
