### ISSUE TITLE
About the FFTConv2d

### ISSUE THREAD

**Issue by Jian-danai** [jnjaby/DISCNet#13]
Hi, I was wondering whether the FFTConv2d in your _data_simulation.py_ is similar to Conv2d and is just used for faster convolution speed?
Or it's more like a pointwise Conv2D?

**Comment by jnjaby** [comment]
Hi, theoretically FFTConv in frequency domain would produce the same results as Conv in spatial domain (depending on the implementation details in the backend). But as we have a large size kernel, it would be much easier and less redundant to implement the convolution in frequency domain. I suppose you can get similar results by pointwise Conv2D with large padding sizes and more FLOPs (`800x800` Multiply-Add per pixel)

**Comment by Jian-danai** [comment]
>
