### ISSUE TITLE
measure my own psf code

### ISSUE THREAD

**Issue by SuyueLiu** [jnjaby/DISCNet#15]
Hi,

Thanks for your impressive work on the UDC image restoration task, I got two questions about the detail,

1. How can I measure the PSF code from my own UDC phone?
2. As mentioned in the main paper, you combined the linear HDR image as the real UDC dataset, how did you dump the raw/linear HDR images without non-linear processing?

Best regards

**Comment by jnjaby** [comment]
Hi,
To measure the PSF, you need to place a white point illuminant (better D65 daylight) at 1-meter away from the camera and capture multiple exposures to fuse them into one HDR image. You can adjust the distance between the illuminant and the camera, depending on the size of the illuminant.

Android provides APIs to dump the raw data from camera, you can refer to [link](https://stackoverflow.com/questions/14777953/how-to-capture-raw-image-from-android-camera) and [link](https://stackoverflow.com/questions/35987346/getting-the-raw-camera-data-on-android). If you are using iPhone, you can consider downloading the ProRAW app.

**Comment by SuyueLiu** [comment]
> Hi, To measure the PSF, you need to place a white point illuminant (better D65 daylight) at 1-meter away from the camera and capture multiple exposures to fuse them into one HDR image. You can adjust the distance between the illuminant and the camera, depending on the size of the illuminant.
> 
> Android provides APIs to dump the raw data from camera, you can refer to [link](https://stackoverflow.com/questions/14777953/how-to-capture-raw-image-from-android-camera) and [link](https://stackoverflow.com/questions/35987346/getting-the-raw-camera-data-on-android). If you are using iPhone, you can consider downloading the ProRAW app.

Ok, I got it, thanks for your reply
