### ISSUE TITLE
A few questions about PSF

### ISSUE THREAD

**Issue by wyxprogramming** [jnjaby/DISCNet#17]
Hi,as for PSF mentioned in the paper, I have the following questions,
The first question is how do you set up your point lights,
The second question is how do you solve the energy cut-off.
Looking forward to your reply. Thank you.

**Comment by jnjaby** [comment]
Hi, for camera setup, please refer to https://github.com/jnjaby/DISCNet/issues/15#issuecomment-1013645741.
I don't quite understand the second question. What do you mean by energy cut-off? Can you make it more specific?
