### ISSUE TITLE
How did you preprocess the HDRI haven Data

### ISSUE THREAD

**Issue by Jian-danai** [jnjaby/DISCNet#19]
I find your ground-truth data range is [0,500] (the maximum is 500.0), so I wonder if you clipped the hdri haven data? Is it still linear data？ I think clipping degraded input is reasonable (as you did in data simulation), but it seems you also clipped the ground-truth data?

Thanks!!

For example, the maximum pixel value for "the_lost_city_4k.hdr" is 143360, which is much bigger than 500.

**Comment by jnjaby** [comment]
Hi, we clip the original HDR data from HDRI Haven to avoid extreme cases. For example, if the picturing values are too large, the induced flare could affect the whole image.
We can regrade the clipping as darkening the light area in the real scene, as the data simulation is performed on the clipped _ground-truth_ data. The network is also built and trained to restore the clipped _ground-truth_ images.
You may try to build up a dataset on unclipped data. But that would require extra efforts on data decontamination and network designs to avoid _inpainting_ the near-saturated light source.
