### ISSUE TITLE
'fov', 'theta', 'phi' meaning

### ISSUE THREAD

**Issue by ohjunee** [jnjaby/DISCNet#2]
what do 'fov', 'theta', and 'phi' mean in text files which are in kernel_info_list directory?

**Comment by jnjaby** [comment]
Hi @ohjunee, 'fov', 'theta', 'phi' are the parameters we set to reproject the panorama HDR images to different views of sub-images [800*800]. Changing these parameters can generate more or less sub-images, with overlap regions.
