### ISSUE TITLE
About the PSF of real data

### ISSUE THREAD

**Issue by yongzhangwhu** [jnjaby/DISCNet#20]
Hi,  I am sorry to bother you and thank you for your innovative contributions in this work. 
   i have some questions about the psf used for testing the real data that how did you get the corresponding psf for the real data ? Did you examine it like the noise in noisy image, or share the psf obtained from the same device?

Best regards

**Comment by jnjaby** [comment]
Hi, as described in the paper, the PSF is captured by the same device. So we use the center PSF for real data.
In this paper, we mainly focus on the characteristic of diffraction artifacts, so noise is excluded in synthetic images. To be consistent, we select real images that are captured in the daytime to reduce noise.

**Comment by yongzhangwhu** [comment]
> 

I have understood this work and thank you for your reply !
