### ISSUE TITLE
datasets,md

### ISSUE THREAD

**Issue by a2900734553** [jnjaby/DISCNet#3]
when run  "python data_scripts/data_simulation.py --data_path=. --psf_type=ZTE_new",I meet a trouble,the error is "OSError: 1920000 requested and 992224 written",so what is the matter

**Comment by jnjaby** [comment]
I didn't encounter this problem before. Can you provide a screenshot or the error traceback of this error?

**Comment by a2900734553** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jnjaby/DISCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月15日(星期四) 下午3:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jnjaby/DISCNet] datasets,md (#3)





 
I didn't encounter this problem before. Can you provide a screenshot or the error traceback of this error?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much,I have solved this error,and i want to know that if i want to use this net to address low light problem,can i use general （such as zed camera) to take images.thank you very much.

**Comment by jnjaby** [comment]
Surely you can train the DISCNet on your own dataset. But you may need to do slight modifications on the Condition Encoder, say, what to feed to the encoder as guidance in your experiment settings.

**Comment by a2900734553** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jnjaby/DISCNet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月16日(星期五) 中午11:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jnjaby/DISCNet] datasets,md (#3)





 
Surely you can train the DISCNet on your own dataset. But you may need to do slight modifications on the Condition Encoder, say, what to feed to the encoder as guidance in your experiment settings.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

Thank you very much,I seem to understand a little.furthermore,I think the documents&nbsp; that you have written are perfect,so if it's convenient,can we&nbsp;  can leave a contact information.do you have a wechat?I am from beijing institue&nbsp; of technology university ，China.Thank you again.

**Comment by jnjaby** [comment]
Hi, if you have further questions about the code and paper, feel free to drop me an email at ruicheng002@ntu.edu.sg
