### ISSUE TITLE
Are the UDC PSFs you released the kernels of UDC actually?

### ISSUE THREAD

**Issue by HyZhu39** [jnjaby/DISCNet#4]
Hello, I tried to visualization the kernels under the path "DISCNet-main/datasets/PSF/ZTE_new".
Because these kernels are used to generate UDC simulation images, then these kernels should be very similar to the paper, with large support, long-tail shape.
While I visualized these kernels as grayscale images, but got results like this：
![ZTE_new_psf_1_0](https://user-images.githubusercontent.com/33981458/129670044-53000ec5-e8e2-48a7-b824-a26a4606049e.jpg)
Obviously, this is the kernel of the standard camera. Is there a problem with my visualization method or the kernel you released is wrong?

here is my visualization code:
data = np.load(path)
data_ = data.transpose(2, 0, 1)  # to  CHW
'''for normalizaion'''
smax = np.max(data_)
smin = np.min(data_)
s = (data_ - smin) / (smax - smin)
s *= 255.
im = Image.fromarray(s[i]).convert('L') #Visualize the i-th channel
im.save(save path)

**Comment by jnjaby** [comment]
Hi, as stated in the paper, the main response has much greater energy with orders of magnitude than the sidelobe. Hence, to visualize the diffraction effect (flare), you will need to increase the intensity of sidelobe regions, which is also the major motivation to consider HDR images. I provide an example of visualization for your reference as follows.

```
import numpy as np
import matplotlib.pyplot as plt

PSF = np.load(path)
PSF = np.clip(PSF * 5000, 0, 1)

plt.imshow(PSF)
plt.axis('off')
plt.tight_layout()
plt.show()
```

**Comment by HyZhu39** [comment]
> Hi, as stated in the paper, the main response has much greater energy with orders of magnitude than the sidelobe. Hence, to visualize the diffraction effect (flare), you will need to increase the intensity of sidelobe regions, which is also the major motivation to consider HDR images. I provide an example of visualization for your reference as follows.
> 
> ```
> import numpy as np
> import matplotlib.pyplot as plt
> 
> PSF = np.load(path)
> PSF = np.clip(PSF * 5000, 0, 1)
> 
> plt.imshow(PSF)
> plt.axis('off')
> plt.tight_layout()
> plt.show()
> ```

got it, thanks a lot.
