### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by cxzhou95** [jnjaby/DISCNet#5]
Hi @jnjaby, thank you for sharing the codes and pretrained models.

I got the issue 'RuntimeError: CUDA out of memory. Tried to allocate 3.01 GiB (GPU 0; 11.77 GiB total capacity; 3.59 GiB already allocated; 3.03 GiB free; 6.78 GiB reserved in total by PyTorch)' when I run 'python -u basicsr/test.py -opt "options/test/DISCNet_test_real_data.yml" --launcher="none"'

Could you tell me your GPU type and memory size?

**Comment by jnjaby** [comment]
Hi, for testing large images, you can consider cropping them into sub-images. Please refer to https://github.com/jnjaby/DISCNet/issues/1. We have this function implemented in https://github.com/jnjaby/DISCNet/blob/63b1859519091f8790afcc47e8c726cbefdcd0fe/basicsr/models/psf_res_model.py#L125

**Comment by cxzhou95** [comment]
Thank you for your help.

**Comment by Jian-danai** [comment]
Hi, for training, what GPU do you use? Can I simply crop the images and feed them into the network?
