### ISSUE TITLE
Could you release the supplemental material?

### ISSUE THREAD

**Issue by cxzhou95** [jnjaby/DISCNet#8]
Hi, I would like to know more details about the simulated data, which can be found in your supplemental material of paper review. Could you please release it?

Another small question: Are the 9 PSFs in 'datasets/PSF/ZTE_new/', e.g., ZTE_new_psf_1, ZTE_new_psf_2, ..., ZTE_new_psf_9 rotated from one captured/measured PSF? For example, ZTE_new_psf_5 is the real captured one, other 8 psfs are ratated with different degrees from (-12, 12).

Looking forward to your reply. Thank you.

**Comment by jnjaby** [comment]
Sorry, I don't quite understand what you are after. Can you be more specific? If you are looking for data simulation process, please refer to [this](https://github.com/jnjaby/DISCNet/blob/main/datasets/data_scripts/data_simulation.py).

For the second question, that's correct. Only the PSF (`ZTE_new_psf_5`) at the center is the real captured one, the rest are generated by applying affine transformation.

Hope this can help.

**Comment by cxzhou95** [comment]
Thank you for your reply. Let me explain my first question.
In your paper Page 4, Section 3.3 Data Collection and Simulation. After you give the description of simulated data, you write "Refer to the Supplemental Material for more details". My question is that could you release this Supplemental Material?

**Comment by jnjaby** [comment]
We have published supplementary files on [arXiv](https://arxiv.org/abs/2104.09556). In section 4 (**Training Details**) we provide details of choices of tone-mapping function, hyper-parameter, and _etc_. All can also be found in the code of data simulation.
